# App of Apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: argocd  # ArgoCD's namespace
  annotations:
    argocd.argoproj.io/sync-wave: "1" #network policy will be created second according to priority
spec:
  project: default
  source:
    repoURL: https://github.com/RajavamshiA/argocd-deployment.git
    targetRevision: main   # or a tag/commit hash
    path: network-policies        # folder in repo with Kubernetes YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true           # delete resources not in Git
      selfHeal: true        # revert out-of-band changes
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true